---
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: package

- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo