---
- name: Download Golang
  get_url:
    url: "https://go.dev/dl/go1.18.3.linux-amd64.tar.gz"
    dest: "{{tmp_file}}"
    force_basic_auth: yes

- name: Extract Golang
  shell: "tar -C /usr/local -xzf {{tmp_file}}"         

- name: Setting GOROOT
  lineinfile:
    path: /home/{{ lookup('env', 'USER') }}/.zshrc
    line: export GOROOT=/usr/local/go/bin
    insertafter: EOF

- name: Adding GOROOT to PATH
  lineinfile:
    path: /home/{{ lookup('env', 'USER') }}/.zshrc
    line: export PATH=$PATH:$GOROOT
    insertafter: EOF

- name: Setting GOPATH
  lineinfile:
    path: /home/{{ lookup('env', 'USER') }}/.zshrc
    line: export GOPATH=/home/{{ lookup('env', 'USER') }}/go
    insertafter: EOF        

- name: Adding GOPATH to PATH
  lineinfile:
    path: /home/{{ lookup('env', 'USER') }}/.zshrc
    line: export PATH=$GOPATH/bin:$PATH
    insertafter: EOF  
