---
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: package     

- include: fedora.yml
  when: ansible_distribution == 'Fedora'
  tags: package   

- name: Inserting zsh to bashrc
  lineinfile:
    path: /home/{{ lookup('env', 'USER') }}/.zshrc
    line: alias bat=batcat
    insertafter: EOF