---
- hosts: all
  become: yes
  tasks:
    - name: Install Bat
      apt:
        name:
          - bat 
    - name: Inserting zsh to bashrc
      lineinfile:
        path: /home/{{ansible_user}}/.zshrc
        line: alias bat=batcat
        insertafter: EOF
