---
- hosts: all  
  become: yes
  tasks:
    - name: Install Pre-Requisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates 
          - curl
          - nano
          - htop
          - gnupg-agent
          - software-properties-common
          - python3-docker
          - zsh
          - git
          - gnupg
          - lsb-release
          - python3-pip          
        update_cache: yes