---
- hosts: all
  become: yes
  tasks:
    - name: Delete existing executable
      file:
        path: "/usr/local/bin/mcfly"
        state: absent

    - name: Install MCFly
      shell: "curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sh -s -- --git cantino/mcfly" 
      
    - name: Inserting zsh to bashrc
      lineinfile:
        path: /home/{{ansible_user}}/.zshrc
        line: eval "$(mcfly init zsh)"
        insertafter: EOF