---
- hosts: all
  become: yes
  tasks:
    - name: Add Sublime Apt key
      ansible.builtin.apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Add Sublime Repo
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/

    - name: Install Sublime
      apt:
        name: 
          - sublime-text
        update_cache: yes